CREATE TYPE "Role" AS ENUM (
  'admin',
  'editor',
  'viewer'
);

CREATE TABLE "Board" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(20) NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "TaskGroup" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(20) NOT NULL,
  "boardId" int NOT NULL
);

CREATE TABLE "Task" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(20) NOT NULL,
  "description" VARCHAR(20) NOT NULL,
  "taskGroupId" int NOT NULL
);

CREATE TABLE "Subtask" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(20) NOT NULL,
  "taskId" int NOT NULL,
  "isCompleted" bool NOT NULL
);

CREATE TABLE "BoardUser" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "boardId" int NOT NULL,
  "userId" int NOT NULL,
  "role" Role NOT NULL,
  PRIMARY KEY ("boardId", "userId")
);

CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE UNIQUE INDEX ON "TaskGroup" ("name", "boardId");

CREATE UNIQUE INDEX ON "Task" ("name", "taskGroupId");

CREATE UNIQUE INDEX ON "Subtask" ("title", "taskId");

ALTER TABLE "TaskGroup" ADD FOREIGN KEY ("boardId") REFERENCES "Board" ("id");

ALTER TABLE "Task" ADD FOREIGN KEY ("taskGroupId") REFERENCES "TaskGroup" ("id");

ALTER TABLE "Subtask" ADD FOREIGN KEY ("taskId") REFERENCES "Task" ("id");

ALTER TABLE "BoardUser" ADD FOREIGN KEY ("boardId") REFERENCES "Board" ("id");

ALTER TABLE "BoardUser" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");
